A You are in the plains
B You are in the plains
C You are in the plains
D You are in the plains
E You are in the plains
F You are in the mountains, painful
G You are in the mountains; you found a cheese burger, yay!
H You are in the plains
I You are in the plains
J You are in the plains
K You are in the plains
L You are in the plains; you found ice cream, yay!
M You are in the mountains, painful
N You are in the mountains, painful
O You are in the river, even more painful than the mountains
P You are in the river, even more painful than the mountains
Q You are in the river, even more painful than the mountains
R You are in the river, even more painful than the mountains
S You are in the mountains, painful
T You are in the mountains, painful
U You are in the mountains, painful
V You are in the mountains, painful
W You are in the mountains, painful
X You are in the mountains, painful
Y You are in the mountains, painful
Z You are in the mountains; you found money, yay!

